### ISSUE TITLE
Cannot read property 'baseUrl' of null

### ISSUE THREAD

**Issue by rochdev** [AdamNowotny/BuildReactor#63] opened 2017-03-22 12:24 UTC
When configuring Jenkins (2.32.2), it shows my projects as "disabled" and there is an error message `Cannot read property 'baseUrl' of null` in the developer console.

**Comment by AdamNowotny** [comment] 2017-03-22 12:28
Is there any stacktrace?

**Comment by rochdev** [comment] 2017-03-22 12:31
It seems I am unable to reproduce the error. However, my projects still show as "disabled". What does "disabled" mean in BuildReactor?

**Comment by rochdev** [comment] 2017-03-22 12:43
If I add it anyway it shows as "offline" in the BuildReactor menu.

**Comment by AdamNowotny** [comment] 2017-03-23 11:40
In case of Jenkins disabled means that "buildable" property on a job is set to false in response of [jenkins_server_base]/api/json?tree=jobs[name,buildable],primaryView[name],views[name,url]
To see the actual error and responses you need to open console for the background page. It's available when you go to extensions page and enable "developer mode".

**Comment by rochdev** [comment] 2017-03-23 11:42
It seems to be receiving 404s on each poll interval

**Comment by AdamNowotny** [comment] 2017-03-23 12:33
Just checked with https://ci.jenkins.io/ and seems like what you describe. Looks like there was a change in Jenkins API since last time I used it...

**Comment by AdamNowotny** [comment] 2017-04-11 11:23
Duplicate of #25

**Comment by AdamNowotny** [comment] 2017-05-17 14:25
Jenkins integration rewritten in version 1.0.0

**Closed by AdamNowotny** 2017-05-17 14:25 UTC
Labels: Jenkins
