### ISSUE TITLE
Sync Extension Data

### ISSUE THREAD

**Issue by colemickens** [AdamNowotny/BuildReactor#54] opened 2016-08-23 22:32 UTC
My Jenkins is auth'd via GitHub OAuth. Meaning the auth I enter in BuildReactor is a personal access token. I don't really want to create 6 different tokens for my 6 machines. I'd prefer BuildReactor synced the configuration using the data sync apis available to Chrome extensions.

**Comment by AdamNowotny** [comment] 2017-05-18 12:23
Duplicate of #33

**Closed by AdamNowotny** 2017-05-18 12:23 UTC
